lista=[8,5,2]
num = len(lista)
print(num)
lista.append(10)
print(lista)
lista.insert(1, 4)
print(lista)
del(lista[1])
print(lista)
lista.remove(10)
print(lista)
valor = lista.pop(1)
print(lista)
lista1=['j','a','g','b']
lista2=sorted(lista1)
print(lista1)
print(lista2)
lista1.sort()
print(lista1)
